### ISSUE TITLE
www-plugins/freshplayerplugin: need to inherit cmake instead of cmake-utils

### ISSUE THREAD

**Issue by Universebenzene** [prototype99/didos#76]
```
Calculating dependencies | * ERROR: www-plugins/freshplayerplugin-0.3.9-r3::didos failed (depend phase):
 *   cmake-utils.eclass could not be found by inherit()
 * 
 * Call stack:
 *                           ebuild.sh, line 618:  Called source '/var/lib/layman/didos/www-plugins/freshplayerplugin/freshplayerplugin-0.3.9-r3.ebuild'
 *   freshplayerplugin-0.3.9-r3.ebuild, line   6:  Called inherit 'cmake-utils'
 *                           ebuild.sh, line 264:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=www-plugins/freshplayerplugin-0.3.9-r3::didos'`,
 * the complete build log and the output of `emerge -pqv '=www-plugins/freshplayerplugin-0.3.9-r3::didos'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/var/tmp/portage/www-plugins/freshplayerplugin-0.3.9-r3/work/freshplayerplugin-0.3.9'
```

The `cmake-utils.eclass` was just [removed from main tree](https://github.com/gentoo-mirror/gentoo/commit/3e744f5adb5c46eb013d3f1228f607b094ac212a) yesterday. Ebuilds using cmake-utils.eclass should change to cmake.eclass instead.

**Comment by prototype99** [comment]
should be fixed now

**Comment by Universebenzene** [comment]
@prototype99 It was not fixed. [This line](https://github.com/prototype99/didos/blob/7f00c3ecbe8a5871fff44af78c08f64bbca78780/www-plugins/freshplayerplugin/freshplayerplugin-0.3.9-r4.ebuild#L76) should be `cmake_src_configure` after the update, not still `cmake-utils_src_configure`

**Comment by prototype99** [comment]
ahhh okay, haven't had gentoo installed for a bit so wasn't able to test it, that is fixed now
